<?php


namespace app\commands;


use manage\library\weChat\WTemplate;
use yii\console\Controller;
use Pheanstalk\Pheanstalk;

class SendController extends Controller
{
    public static $beanstalk;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $beanstalkConf = \Yii::$app->components['beanstalk'];
        self::$beanstalk = new Pheanstalk($beanstalkConf['hostname'], $beanstalkConf['port']);
    }

    public function actionDelayUpdate()
    {
//        $n=11;
        while (true) {
            $data = $this->reserve('send_task',300);
            var_dump($data);
            if($data){
                $data = json_decode($data,true);
                $this->handleTast($data['task_id']);
            }
            //TODO  process biz
        }

        return true;
    }


    private function reserve($channel, $processTime = 3)
    {
        $job = self::$beanstalk->watch($channel)
            ->ignore('default')
            ->reserve($processTime);

        $jobData = null;
        if ($job) {
            $jobData = $job->getData();
            self::$beanstalk->delete($job);
        }

        return $jobData;
    }

    private function handleTast($send_id){
        $start_time = microtime(true);
        $sendBo = new \manage\models\send\bo\Index();
        //获取推送详情
        $send_detail = $sendBo->getSendDetail($send_id);
        if(!$send_detail){
            //如果消息不存在，则清除掉队列中的send_id
            $sendBo->delTaskId($send_id);
            return false;
        }
        $send_num = 0;//推送人次
        if($send_detail['openids']){
            $openid_arr = explode(',',$send_detail['openids']);
            $send_num = count($openid_arr);
            $this->_sendOpenidtemplate($send_detail['openids'],$send_detail);
        }else{
            //获取用户信息formid进行推送
            $num = 0;
            //循环取出每一个user_formid_list:uid
            while(($userlist = $sendBo->scan($num,['match'=>'user_formid_list:*'])) ){
                foreach ($userlist[1] as $userkey){
                    $user_id = substr($userkey,17);
                    $formid = $sendBo->getUserFormid($user_id);
                    if($formid){
                        $this->_sendtemplate($user_id,$formid,$send_detail);
                        $send_num++;
                    }else{
                        continue;
                    }
                }
                $num = $userlist[0];//偏移量
                if($num==0){
                    break;
                }
            }
        }
        if($send_num==0) $send_num = 1;
        $sendBo->updateSendNum($send_id,$send_num);
        $sendBo->delTaskId($send_id);

        $end_time =  microtime(true);
        $sum_time = $end_time-$start_time;
        echo 'sum_time: '. $sum_time;
    }

    public function actionTest($formid){
        echo $formid;
//        \Yii::warning('this is info test');
//        $sendBo = new \manage\models\send\bo\Index();
//        $result = $sendBo->getOpenidByUserId(6);
//        $result = $sendBo->getUserIdByOpenid('test_codecodecodecodecodecode');
//        var_dump($result);
        $res = WTemplate::pushArticle('o1XVc5fhcD6DWZbmhZOLxKkwCbTw',1,$formid,'title','2018-06-22','');
        var_dump($res);

    }

    //进行推送
    private function _sendtemplate($user_id,$formid,$send_detail){
        $data = [
            'user_id'=>$user_id,
            'formid'=>$formid,
            'url'=>$send_detail['url'],
            'url_id'=>$send_detail['url_id'],
            'title'=>$send_detail['title'],
            'publish_time'=>$send_detail['publish_time'],
            'description'=>$send_detail['description']
        ];
        self::$beanstalk->useTube('template')->put(json_encode($data));
        echo 'send formid:'.$user_id.'-'.$formid.'-'."\n";
    }

    //给指定用户推送
    private function _sendOpenidtemplate($openids,$send_detail){

        $data = [
            'openids'=>$openids,
            'url'=>$send_detail['url'],
            'url_id'=>$send_detail['url_id'],
            'title'=>$send_detail['title'],
            'publish_time'=>$send_detail['publish_time'],
            'description'=>$send_detail['description']
        ];
        self::$beanstalk->useTube('template')->put(json_encode($data));
        echo 'send formid:'.'-'.$openids.'-'."\n";

    }

}