<?php


namespace app\commands;

use manage\library\weChat\WTemplate;
use yii\console\Controller;
use Pheanstalk\Pheanstalk;

class TemplateController extends Controller
{
    public static $beanstalk;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $beanstalkConf = \Yii::$app->components['beanstalk'];
        self::$beanstalk = new Pheanstalk($beanstalkConf['hostname'], $beanstalkConf['port']);
    }

    public function actionDelayUpdate()
    {
//        $n=11;
        while (true) {
            $data = $this->reserve('template');
            var_dump($data);
            //TODO  process biz
            if($data){
                $this->handleTast(json_decode($data,true));
            }
        }

        return true;
    }


    private function reserve($channel, $processTime = 3)
    {
        $job = self::$beanstalk->watch($channel)
            ->ignore('default')
            ->reserve($processTime);

        $jobData = null;
        if ($job) {
            $jobData = $job->getData();
            self::$beanstalk->delete($job);
        }

        return $jobData;
    }

    private function handleTast($data){
        if(isset($data['openids'])){
            $this->_sendOpenidtemplate($data);
        }else{
            $this->_sendtemplate($data);
        }
    }

    //进行推送
    private function _sendtemplate($data){
        $sendBo = new \manage\models\send\bo\Index();
        $result = $sendBo->getOpenidByUserId($data['user_id']);
        $openid = $result['openid'];
        $ret = WTemplate::pushArticle($openid,$data['url'],$data['url_id'],$data['formid'],$data['title'],$data['publish_time'],$data['description']);
        var_dump($ret);
        echo 'send formid:'.$data['user_id'].'-'.$data['formid'].'-'.$openid."\n";
    }

    //给指定用户推送
    private function _sendOpenidtemplate($data){
        $openid_arr = explode(',',$data['openids']);
        $sendBo = new \manage\models\send\bo\Index();
        foreach ($openid_arr as $openid){
            //根据openid查询user_id
            $result = $sendBo->getUserIdByOpenid($openid);
            $user_id = $result['id'];
            $formid = $sendBo->getUserFormid($user_id);
            $ret = WTemplate::pushArticle($openid,$data['url'],$data['url_id'],$formid,$data['title'],$data['publish_time'],$data['description']);
            var_dump($ret);
            echo 'send formid:'.$user_id.'-'.$formid.'-'.$openid."\n";
        }
    }

}