<?php
/***************************************************************************
 *
 * Copyright (c) 2018 sunlands.com, Inc. All Rights Reserved
 *
 ***************************************************************************/



/**
 * Created by PhpStorm.
 * User: charlie
 * Date: 2018/5/17
 * Time: 下午8:11
 */

namespace manage\controllers\test;

use manage\controllers\MyController;
use manage\library\QueueJob;

class IndexController extends MyController
{

    public function init()
    {
        parent::init();
        if (YII_ENV == 'prod') {
            exit('非法访问');
        }
    }

    public function actionIndex()
    {
        $param = [];


        QueueJob::addQueueJobOfGenerateArticleOssContentImage(9999);


        QueueJob::doQueueJobOfGenerateArticleOssContentImage();



        return $this->_doFunction($param);
    }

    public function actionShotJob()
    {
        $article_id = $this->get("article_id");


        QueueJob::addQueueJobOfGenerateArticleOssContentImage($article_id);


        //QueueJob::doQueueJobOfGenerateArticleOssContentImage();


        return $this->_doFunction($article_id);
    }

    public function actionShot()
    {
        $article_id = $this->get("article_id");

        /** @var ScreenShot $phantomjs */
        $phantomjs = \Yii::$app->phantomjs;

        $res = $phantomjs->shotArticleContentThenUploadToOss($article_id);

        echo json_encode($res);
        exit(200);
        return parent::actions(); // TODO: Change the autogenerated stub
    }

}